#!/usr/bin/env bash
# This script redirect the page to another

sudo apt update
sudo apt install nginx -y
echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
new="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\n\t}\n"
err="\\\n\terror_page 404 /custom_404.html;\n\tlocation /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
sudo sed -i "30i $new" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "48i $err" /etc/nginx/sites-available/default
sudo service nginx restart
