#!/usr/bin/env bash
# This script installs and configures HAproxy

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

echo "
frontend colandru
	bind *:80
	mode http
	default_backend colandrubackend
backend colandrubackend
	balance roundrobin
	option forwardfor
	server 1872-web-01 34.74.115.197:80 check
	server 1872-web-02 54.87.144.17:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
