#!/usr/bin/env bash
#fizzbuzz
num=1
while [ $num -lt 101 ]
do
	if [ $((num % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((num % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((num % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$num"
	fi
	num=$((num + 1))
done
