#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
num="0"
while [ $num -lt 10 ];
do 
	echo "Holberton School"
	if [ "$num" = "8" ]
	then
		echo "Hi"
	fi
	num=$(($num + 1))
done;
