#!/usr/bin/env bash
#1 to 20
num=1
while [ $num -lt 21 ]
do
	echo "$num"
	case $num in 4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	num=$((num + 1))
done
